<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>DeLongHomestay-Development</UserSecretsId>
    <VersionPrefix>1.8.3</VersionPrefix>
  </PropertyGroup>

  <ItemGroup Condition="'$(BuildId)' != ''">
    <AssemblyMetadata Include="BuildId" Value="$(BuildId)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
    <PackageReference Include="ZiggyCreatures.FusionCache" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="artifacts\publish\" />
    <EmbeddedResource Include="Assets/Fonts/*.ttf" />
  </ItemGroup>
</Project>
